TOKEN = "8026512064:AAFSq32IIXkPkXPi7kMl-wM5NoD_gqSmpd0"
ADMIN_ID = 7760459637

COINS = [
    "BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "TRXUSDT", "AVAXUSDT", "SHIBUSDT",
    "LINKUSDT", "DOTUSDT", "NEARUSDT", "LTCUSDT", "UNIUSDT", "PEPEUSDT", "ICPUSDT", "APTUSDT", "HBARUSDT", "CROUSDT",
    "VETUSDT", "MKRUSDT", "FILUSDT", "ATOMUSDT", "IMXUSDT", "OPUSDT", "ARBUSDT", "INJUSDT", "RUNEUSDT", "GRTUSDT"
]

INTERVAL = "15m"
LIMIT = 300
SQUEEZE_THRESHOLD = 0.018
COOLDOWN_MINUTES = 60  # tránh spam cùng coin
